require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CleaningsController do

  # This should return the minimal set of attributes required to create a valid
  # Cleaning. As you add validations to Cleaning, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "date_check" => "2015-11-06" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CleaningsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cleanings as @cleanings" do
      cleaning = Cleaning.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cleanings).should eq([cleaning])
    end
  end

  describe "GET show" do
    it "assigns the requested cleaning as @cleaning" do
      cleaning = Cleaning.create! valid_attributes
      get :show, {:id => cleaning.to_param}, valid_session
      assigns(:cleaning).should eq(cleaning)
    end
  end

  describe "GET new" do
    it "assigns a new cleaning as @cleaning" do
      get :new, {}, valid_session
      assigns(:cleaning).should be_a_new(Cleaning)
    end
  end

  describe "GET edit" do
    it "assigns the requested cleaning as @cleaning" do
      cleaning = Cleaning.create! valid_attributes
      get :edit, {:id => cleaning.to_param}, valid_session
      assigns(:cleaning).should eq(cleaning)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cleaning" do
        expect {
          post :create, {:cleaning => valid_attributes}, valid_session
        }.to change(Cleaning, :count).by(1)
      end

      it "assigns a newly created cleaning as @cleaning" do
        post :create, {:cleaning => valid_attributes}, valid_session
        assigns(:cleaning).should be_a(Cleaning)
        assigns(:cleaning).should be_persisted
      end

      it "redirects to the created cleaning" do
        post :create, {:cleaning => valid_attributes}, valid_session
        response.should redirect_to(Cleaning.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cleaning as @cleaning" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cleaning.any_instance.stub(:save).and_return(false)
        post :create, {:cleaning => { "date_check" => "invalid value" }}, valid_session
        assigns(:cleaning).should be_a_new(Cleaning)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cleaning.any_instance.stub(:save).and_return(false)
        post :create, {:cleaning => { "date_check" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cleaning" do
        cleaning = Cleaning.create! valid_attributes
        # Assuming there are no other cleanings in the database, this
        # specifies that the Cleaning created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cleaning.any_instance.should_receive(:update).with({ "date_check" => "2015-11-06" })
        put :update, {:id => cleaning.to_param, :cleaning => { "date_check" => "2015-11-06" }}, valid_session
      end

      it "assigns the requested cleaning as @cleaning" do
        cleaning = Cleaning.create! valid_attributes
        put :update, {:id => cleaning.to_param, :cleaning => valid_attributes}, valid_session
        assigns(:cleaning).should eq(cleaning)
      end

      it "redirects to the cleaning" do
        cleaning = Cleaning.create! valid_attributes
        put :update, {:id => cleaning.to_param, :cleaning => valid_attributes}, valid_session
        response.should redirect_to(cleaning)
      end
    end

    describe "with invalid params" do
      it "assigns the cleaning as @cleaning" do
        cleaning = Cleaning.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cleaning.any_instance.stub(:save).and_return(false)
        put :update, {:id => cleaning.to_param, :cleaning => { "date_check" => "invalid value" }}, valid_session
        assigns(:cleaning).should eq(cleaning)
      end

      it "re-renders the 'edit' template" do
        cleaning = Cleaning.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cleaning.any_instance.stub(:save).and_return(false)
        put :update, {:id => cleaning.to_param, :cleaning => { "date_check" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cleaning" do
      cleaning = Cleaning.create! valid_attributes
      expect {
        delete :destroy, {:id => cleaning.to_param}, valid_session
      }.to change(Cleaning, :count).by(-1)
    end

    it "redirects to the cleanings list" do
      cleaning = Cleaning.create! valid_attributes
      delete :destroy, {:id => cleaning.to_param}, valid_session
      response.should redirect_to(cleanings_url)
    end
  end

end
