require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MoniksController do

  # This should return the minimal set of attributes required to create a valid
  # Monik. As you add validations to Monik, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "inv_num" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MoniksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all moniks as @moniks" do
      monik = Monik.create! valid_attributes
      get :index, {}, valid_session
      assigns(:moniks).should eq([monik])
    end
  end

  describe "GET show" do
    it "assigns the requested monik as @monik" do
      monik = Monik.create! valid_attributes
      get :show, {:id => monik.to_param}, valid_session
      assigns(:monik).should eq(monik)
    end
  end

  describe "GET new" do
    it "assigns a new monik as @monik" do
      get :new, {}, valid_session
      assigns(:monik).should be_a_new(Monik)
    end
  end

  describe "GET edit" do
    it "assigns the requested monik as @monik" do
      monik = Monik.create! valid_attributes
      get :edit, {:id => monik.to_param}, valid_session
      assigns(:monik).should eq(monik)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Monik" do
        expect {
          post :create, {:monik => valid_attributes}, valid_session
        }.to change(Monik, :count).by(1)
      end

      it "assigns a newly created monik as @monik" do
        post :create, {:monik => valid_attributes}, valid_session
        assigns(:monik).should be_a(Monik)
        assigns(:monik).should be_persisted
      end

      it "redirects to the created monik" do
        post :create, {:monik => valid_attributes}, valid_session
        response.should redirect_to(Monik.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved monik as @monik" do
        # Trigger the behavior that occurs when invalid params are submitted
        Monik.any_instance.stub(:save).and_return(false)
        post :create, {:monik => { "inv_num" => "invalid value" }}, valid_session
        assigns(:monik).should be_a_new(Monik)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Monik.any_instance.stub(:save).and_return(false)
        post :create, {:monik => { "inv_num" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested monik" do
        monik = Monik.create! valid_attributes
        # Assuming there are no other moniks in the database, this
        # specifies that the Monik created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Monik.any_instance.should_receive(:update).with({ "inv_num" => "MyString" })
        put :update, {:id => monik.to_param, :monik => { "inv_num" => "MyString" }}, valid_session
      end

      it "assigns the requested monik as @monik" do
        monik = Monik.create! valid_attributes
        put :update, {:id => monik.to_param, :monik => valid_attributes}, valid_session
        assigns(:monik).should eq(monik)
      end

      it "redirects to the monik" do
        monik = Monik.create! valid_attributes
        put :update, {:id => monik.to_param, :monik => valid_attributes}, valid_session
        response.should redirect_to(monik)
      end
    end

    describe "with invalid params" do
      it "assigns the monik as @monik" do
        monik = Monik.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Monik.any_instance.stub(:save).and_return(false)
        put :update, {:id => monik.to_param, :monik => { "inv_num" => "invalid value" }}, valid_session
        assigns(:monik).should eq(monik)
      end

      it "re-renders the 'edit' template" do
        monik = Monik.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Monik.any_instance.stub(:save).and_return(false)
        put :update, {:id => monik.to_param, :monik => { "inv_num" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested monik" do
      monik = Monik.create! valid_attributes
      expect {
        delete :destroy, {:id => monik.to_param}, valid_session
      }.to change(Monik, :count).by(-1)
    end

    it "redirects to the moniks list" do
      monik = Monik.create! valid_attributes
      delete :destroy, {:id => monik.to_param}, valid_session
      response.should redirect_to(moniks_url)
    end
  end

end
